name: 3dunet

channels:
  - pytorch
  - conda-forge

dependencies:
  - python 3.9
  - pytorch
  - tensorboard
  - tqdm
  - setuptools
  - h5py
  - onnx
  - scipy
  - scikit-image
  - pyyaml
  - pytest
